missing categorical values

In [102]:
import pandas as ps
import numpy as np
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [57]:
df=ps.read_csv('/content/Airplane_Crashes_and_Fatalities_Since_1908.csv')

In [89]:
df.sample(5)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
4306,12/17/1994,13:20,None,None,NaN,Tabubil - Selbang,de Havilland Canada DHC-6 Twin Otter 200,P2-MFS,187,28.0,28.0,0.0,"The chartered flight struck a cliff at 6,400 f..."
3892,10/21/1989,07:53,None,None,414,Managua - Tegucigalpa,Boeing B-727-224,N88705,19514/597,146.0,127.0,0.0,The aircraft landed short of the runway in hea...
3209,03/21/1980,NaN,None,None,NaN,NaN,Sikorsky S-76,PT-HKB,760008,14.0,14.0,0.0,Crashed into the sea.
4061,11/21/1991,NaN,None,None,NaN,NaN,Yakovlev YAK-40,NaN,NaN,20.0,20.0,0.0,NaN
2153,07/25/1967,10:30,None,None,NaN,Vientiane - Luang Prabang,Douglas DC-3,XW-PDL,NaN,16.0,16.0,0.0,Struck a mountain in the Phou Pha Bon range wh...

In [90]:
df.isnull().mean()*100

Date              0.000000
Time             42.122248
Location        100.000000
Operator        100.000000
Flight #         79.707669
Route            32.403189
Type              0.512528
Registration      6.359150
cn/In            23.310554
Aboard            0.417616
Fatalities        0.227790
Ground            0.417616
Summary           7.403189
dtype: float64

In [91]:
df.columns

Index(['Date', 'Time', 'Location', 'Operator', 'Flight #', 'Route', 'Type',
       'Registration', 'cn/In', 'Aboard', 'Fatalities', 'Ground', 'Summary'],
      dtype='object')

In [98]:
sam=df.drop(columns=['Date', 'Location'	,'Operator','Time','Flight #','Registration', 'cn/In', 'Aboard',  'Ground'])

In [108]:
sam.sample(2)

,Route,Type,Fatalities,Summary
88,NaN,de Havilland DH-34B,8.0,"Shortly after taking off, witnesses observed a..."
834,"Flint, MI - Washville, IL",Douglas C-47A,2.0,The cargo plane crashed after both engines fai...

In [109]:
sam.isnull().mean()*100

Route         32.403189
Type           0.512528
Fatalities     0.227790
Summary        7.403189
dtype: float64

In [110]:
fea=sam.drop(columns=['Fatalities'])
tar=sam['Fatalities']

xtrain,xtest,ytrain,ytest=train_test_split(fea,tar,test_size=0.2)

In [111]:
ct=ColumnTransformer(
    transformers=[
        ('t1',SimpleImputer(strategy='most_frequent'),['Route','Type','Summary'])
    ],
    remainder='passthrough'
)

In [112]:
xtraintrans=ct.fit_transform(xtrain)
xtesttrans=ct.transform(xtest)

In [113]:
xtrain.isnull().sum()

Route      1375
Type         21
Summary     311
dtype: int64

In [116]:
x=ps.DataFrame(xtraintrans)

In [117]:
x

,0,1,2
0,Training,Short S-26 (flying boat),Crashed during takeoff.
1,"Newark, NJ - Boston, MA",McDonnell Douglas DC-10-30CF,"While landing on an icy runway, the aircraft t..."
2,Training,Lockheed L-18-56 Lodestar,Flew into a hill shortly after talking off fro...
3,"Las Vegas, NV - Riverside, CA",Piper PA-32,Crashed into cables and caugt fire after a thi...
4,Training,Consolidated LB-30A Liberator,The aircraft crashed into a hill shortly after...
...,...,...,...
4209,Training,Douglas C-47A,The cargo plane crashed into a mountain.
4210,Puerto Vallarta - San Francisco,McDonnell Douglas MD-83,The aircraft crashed into the PacifiOcean sout...
4211,Tapacula - Mexico City,Douglas DC-3,"Crashed into a 15,000 ft. snow covered volcano..."
4212,Training,Douglas C-47B,"The student pilot rotated too quickly, the pla..."
4213,"Lakehurst, NJ - S.t Louis, MO",Dirigible ZR-1 Shenandoah (airship),The Shenandoah was flying over Southern Ohio w...

In [120]:
x.isnull().sum()

0    0
1    0
2    0
dtype: int64